{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": []
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "code",
      "execution_count": 1,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 1000
        },
        "id": "yPzflsUqgT-V",
        "outputId": "30ae41b2-f5fb-491e-c2f3-51ac30154c00"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/base_command.py\", line 179, in exc_logging_wrapper\n",
            "    status = run_func(*args)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/req_command.py\", line 67, in wrapper\n",
            "    return func(self, options, args)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/pip/_internal/commands/install.py\", line 324, in run\n",
            "    session = self.get_default_session(options)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/index_command.py\", line 71, in get_default_session\n",
            "    self._session = self.enter_context(self._build_session(options))\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/index_command.py\", line 100, in _build_session\n",
            "    session = PipSession(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/pip/_internal/network/session.py\", line 344, in __init__\n",
            "    self.headers[\"User-Agent\"] = user_agent()\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/pip/_internal/network/session.py\", line 177, in user_agent\n",
            "    setuptools_dist = get_default_environment().get_distribution(\"setuptools\")\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/pip/_internal/metadata/__init__.py\", line 76, in get_default_environment\n",
            "    return select_backend().Environment.default()\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/pip/_internal/metadata/__init__.py\", line 64, in select_backend\n",
            "    from . import pkg_resources\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/pip/_internal/metadata/pkg_resources.py\", line 16, in <module>\n",
            "    from pip._vendor import pkg_resources\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/pip/_vendor/pkg_resources/__init__.py\", line 3292, in <module>\n",
            "    def _initialize_master_working_set():\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/pip/_vendor/pkg_resources/__init__.py\", line 3266, in _call_aside\n",
            "    f(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/pip/_vendor/pkg_resources/__init__.py\", line 3324, in _initialize_master_working_set\n",
            "    list(map(working_set.add_entry, sys.path))\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/pip/_vendor/pkg_resources/__init__.py\", line 640, in add_entry\n",
            "    for dist in find_distributions(entry, True):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/pip/_vendor/pkg_resources/__init__.py\", line 2102, in find_on_path\n",
            "    yield from factory(fullpath)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/pip/_vendor/pkg_resources/__init__.py\", line 2159, in distributions_from_metadata\n",
            "    if len(os.listdir(path)) == 0:\n",
            "KeyboardInterrupt\n",
            "\n",
            "During handling of the above exception, another exception occurred:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/bin/pip3\", line 8, in <module>\n",
            "    sys.exit(main())\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/main.py\", line 80, in main\n",
            "    return command.main(cmd_args)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/base_command.py\", line 100, in main\n",
            "    return self._main(args)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/base_command.py\", line 232, in _main\n",
            "    return run(options, args)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/base_command.py\", line 215, in exc_logging_wrapper\n",
            "    logger.critical(\"Operation cancelled by user\")\n",
            "  File \"/usr/lib/python3.10/logging/__init__.py\", line 1524, in critical\n",
            "    self._log(CRITICAL, msg, args, **kwargs)\n",
            "  File \"/usr/lib/python3.10/logging/__init__.py\", line 1624, in _log\n",
            "    self.handle(record)\n",
            "  File \"/usr/lib/python3.10/logging/__init__.py\", line 1634, in handle\n",
            "    self.callHandlers(record)\n",
            "  File \"/usr/lib/python3.10/logging/__init__.py\", line 1696, in callHandlers\n",
            "    hdlr.handle(record)\n",
            "  File \"/usr/lib/python3.10/logging/__init__.py\", line 968, in handle\n",
            "    self.emit(record)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/pip/_internal/utils/logging.py\", line 177, in emit\n",
            "    self.console.print(renderable, overflow=\"ignore\", crop=False, style=style)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/pip/_vendor/rich/console.py\", line 1685, in print\n",
            "    render_options = self.options.update(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/pip/_vendor/rich/console.py\", line 184, in update\n",
            "    options = self.copy()\n",
            "KeyboardInterrupt\n",
            "^C\n"
          ]
        },
        {
          "output_type": "error",
          "ename": "ModuleNotFoundError",
          "evalue": "No module named 'gpt_2_simple'",
          "traceback": [
            "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
            "\u001b[0;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)",
            "\u001b[0;32m<ipython-input-1-6698204821ba>\u001b[0m in \u001b[0;36m<cell line: 11>\u001b[0;34m()\u001b[0m\n\u001b[1;32m      9\u001b[0m \u001b[0;31m#%tensorflow_version 2.x\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     10\u001b[0m \u001b[0mget_ipython\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msystem\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'pip install -q gpt-2-simple'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 11\u001b[0;31m \u001b[0;32mimport\u001b[0m \u001b[0mgpt_2_simple\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0mgpt2\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     12\u001b[0m \u001b[0;32mfrom\u001b[0m \u001b[0mdatetime\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mdatetime\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     13\u001b[0m \u001b[0;32mfrom\u001b[0m \u001b[0mgoogle\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mcolab\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mdrive\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
            "\u001b[0;31mModuleNotFoundError\u001b[0m: No module named 'gpt_2_simple'",
            "",
            "\u001b[0;31m---------------------------------------------------------------------------\u001b[0;32m\nNOTE: If your import is failing due to a missing package, you can\nmanually install dependencies using either !pip or !apt.\n\nTo view examples of installing some common dependencies, click the\n\"Open Examples\" button below.\n\u001b[0;31m---------------------------------------------------------------------------\u001b[0m\n"
          ],
          "errorDetails": {
            "actions": [
              {
                "action": "open_url",
                "actionText": "Open Examples",
                "url": "/notebooks/snippets/importing_libraries.ipynb"
              }
            ]
          }
        }
      ],
      "source": [
        "import pandas as pd\n",
        "import sys\n",
        "from os import path\n",
        "from nltk.tokenize import word_tokenize\n",
        "from nltk import download\n",
        "from tqdm import tqdm\n",
        "\n",
        "rawData = pd.read_csv('smaller_dataset.csv',usecols=['title','NER','directions'],nrows=1000)\n",
        "# print(rawData.dtypes)\n",
        "# print(rawData.columns)\n",
        "# print(rawData.iloc[0])\n",
        "# print(rawData['directions'][0])\n",
        "\n",
        "colnames = ['title', 'ingredients', 'instructions', 'separator_and_recipe']\n",
        "colnames2 = ['title', 'ingredients', 'separator', 'instructions', 'separator_and_recipe']\n",
        "colnames3 = ['title', 'ingredients', 'separator', 'instructions', 'separator_and_recipe']\n",
        "\n",
        "#1) Originally Parsed Dataset\n",
        "df = pd.DataFrame(columns=colnames)\n",
        "df['title'] = rawData['title']\n",
        "df['ingredients'] = rawData['NER']\n",
        "df['instructions'] = rawData['directions']\n",
        "df['separator_and_recipe'] = '</>separator_and_recipe</>'\n",
        "\n",
        "#2) Parsed Dataset with Seperator Between Ingredient List and Instruction List\n",
        "df2 = pd.DataFrame(columns=colnames2)\n",
        "df2['title'] = rawData['title']\n",
        "df2['ingredients'] = rawData['NER']\n",
        "df2['separator'] = '</>separator</>'\n",
        "df2['instructions'] = rawData['directions']\n",
        "df2['separator_and_recipe'] = '</>separator_and_recipe</>'\n",
        "\n",
        "#3) Parsed Dataset with Seperator Between Each Ingredient Item\n",
        "df3 = pd.DataFrame(columns=colnames3)\n",
        "df3['title'] = rawData['title']\n",
        "df3['ingredients'] = rawData['NER']\n",
        "df3['instructions'] = rawData['directions']\n",
        "df3['separator_and_recipe'] = '</>separator_and_recipe</>'\n",
        "df3['ingredients'] = df['ingredients'].apply(lambda x: x.replace(\",\", \"</>separator</>,\"))\n",
        "\n",
        "#3) Parsed Dataset with Both 2 & 3\n",
        "df4 = pd.DataFrame(columns=colnames3)\n",
        "df4['title'] = rawData['title']\n",
        "df4['ingredients'] = rawData['NER']\n",
        "df4['separator'] = '</>separator</>'\n",
        "df4['instructions'] = rawData['directions']\n",
        "df4['separator_and_recipe'] = '</>separator_and_recipe</>'\n",
        "df4['ingredients'] = df['ingredients'].apply(lambda x: x.replace(\",\", \"</>separator</>,\"))\n",
        "\n",
        "\n",
        "\n",
        "#Shows What Each Part of 'df' Is:\n",
        "print(\"Columns: \\n\", df.columns)\n",
        "print(\"\\n Iloc: \\n\", df.iloc[0])\n",
        "print(\"\\nTitle: \\n\", df['title'][0])\n",
        "print(\"\\nIngredients[0]: \\n\", df['ingredients'][0])\n",
        "print(\"\\nInstructions[0]: \\n\", df['instructions'][0])\n",
        "print(\"\\nSeperator[0]: \\n\", df['separator_and_recipe'][0])\n",
        "print(\"\\nShape: \\n\", df.shape)\n",
        "\n",
        "df.to_csv('df_originally_tokenized_dataset.txt', header = None, sep=' ',index=False,quotechar=\"'\")\n",
        "df2.to_csv('df_tokenized_with_separators_btwn_ingredient_and_instruction_lists.txt', header = None, sep=' ',index=False,quotechar=\"'\")\n",
        "df3.to_csv('df_tokenized_with_separators_btwn_ingredient_items.txt', header = None, sep=' ',index=False,quotechar=\"'\")\n",
        "df4.to_csv('df_tokenized_with_separators_btwn_ingredient_items_and_btwn_lists.txt', header = None, sep=' ',index=False,quotechar=\"'\")"
      ]
    }
  ]
}